### ISSUE TITLE
Move genesis2 installation from `CGRAGenerator/bin/generate.csh` to setup.sh

### ISSUE THREAD

**Issue by leonardt** [StanfordAHA/CGRAFlow#38]
Ideally we have all setup logic outside of the makefile, currently the call to `generate.csh` will result in a `git clone` for genesis2 if it's not present.

**Comment by steveri** [comment]
Sure no problem, I will create a 'genesis2' branch and pull request...

**Comment by steveri** [comment]
Hmmm, tricky, since you have an open pull request; maybe I will wait for that to close before I do this.
And/or if you want to include it in the pull request, it's just a simple matter of adding  this to setup.sh:

  git clone https://github.com/StanfordVLSI/Genesis2.git /tmp/Genesis2

As you probably know, this then short-circuits the later git clone...

**Comment by steveri** [comment]
Hmmm, tricky, since you have an open pull request; maybe I will wait for that to close before I do this.
And/or if you want to include it in the pull request, it's just a simple matter of adding  this to setup.sh:

  git clone https://github.com/StanfordVLSI/Genesis2.git /tmp/Genesis2

As you probably know, this then short-circuits the later git clone...

**Comment by steveri** [comment]
Okay I made the change, it's building now...after it passes I will close out this issue...

**Comment by steveri** [comment]
Looks like it passed!  I'm going to close us out.

https://travis-ci.org/StanfordAHA/CGRAFlow/builds/318777191
